hmcts/darts-stub-services

Jenkinsfile_CNP, build.gradle
=> DMP-816: Adding import

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/darts/stub/services/SampleFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/stub/services/IntegrationTestBase.java, src/integrationTest/java/uk/gov/hmcts/darts/stub/services/WiremockProxyTest.java, src/main/java/uk/gov/hmcts/darts/stub/services/controllers/WiremockProxyController.java, src/smokeTest/java/uk/gov/hmcts/darts/stub/services/SampleSmokeTest.java, src/smokeTest/java/uk/gov/hmcts/reform/darts/controllers/SampleSmokeTest.java, wiremock/mappings/dar/delete_test.json, wiremock/mappings/dar/get_test.json, wiremock/mappings/dar/post_test.json, wiremock/mappings/dar/put_test.json
Adding test coverage for request forwarding
=> DMP-816: Adding test coverage for request forwarding

src/main/java/uk/gov/hmcts/darts/stub/services/config/ApplicationConfig.java, src/main/java/uk/gov/hmcts/darts/stub/services/controllers/WiremockRequestForwardingController.java, wiremock/mappings/dar/dar_mapping.json, wiremock/mappings/test/post_xml_test.json
=> DMP-817: Adding dar mapping

src/main/resources/application.yaml
Temporarily commenting out insights config
```
[ ] Yes
[x] No
```
=> DMP-817 Temporarily commenting out insights config

src/main/resources/application.yaml
=> Adding insights config

src/main/resources/application.yaml
=> Dmp 817 adding mapping for dar notification

src/main/java/uk/gov/hmcts/darts/stub/services/controllers/WiremockRequestForwardingController.java
=> Adding logging

src/main/java/uk/gov/hmcts/darts/stub/services/config/WireMockServerConfig.java, src/main/java/uk/gov/hmcts/darts/stub/services/controllers/WiremockRequestForwardingController.java
=> Dmp 817 wiremock stub

src/main/java/uk/gov/hmcts/darts/stub/services/config/WireMockServerConfig.java
=> Turning off GZIP

src/main/java/uk/gov/hmcts/darts/stub/services/config/WireMockServerConfig.java, src/main/java/uk/gov/hmcts/darts/stub/services/controllers/WiremockRequestForwardingController.java, wiremock/mappings/dar/dar_mapping.json
=> Returning byte array

src/main/java/uk/gov/hmcts/darts/stub/services/controllers/WiremockRequestForwardingController.java
=> Dmp 817 fixing gzip issue

.github/workflows/ci.yml, build.gradle, wiremock/mappings/arm/v3_UpdateMetadata.json
[DMP-1845](https://tools.hmcts.net/jira/browse/DMP-1845)
Add wiremock OK response for ARM Disposition
```
[ ] Yes
[x] No
```
=> DMP-1845 Add wiremock OK response for ARM Disposition: /api/v3/UpdateMetadata

darts-stub-services.postman_collection.json, wiremock/mappings/arm/v3_UpdateMetadata_alt1.json
[DMP-2096](https://tools.hmcts.net/jira/browse/DMP-2096)
Add alternative `"isError": true` response for any event_date < 2024
Also add postman collection
```
[ ] Yes
[x] No
```
=> DMP-2096 ARM Stub - Disposition (Error Flow Only)

darts-stub-services.postman_collection.json
[DMP-2151](https://tools.hmcts.net/jira/browse/DMP-2151)
Update postman collection: GET /api/v1/token
```
[ ] Yes
[x] No
```
=> DMP-2151 Update postman collection: GET /api/v1/token

Dockerfile, wiremock/mappings/arm/v1_DownloadBlob.json
https://tools.hmcts.net/jira/browse/DMP-2223
ARM Stub - DownloadBlob: After sending the endpoint it returns the NotFoundException.
```
[ ] Yes
[X] No
```
=> DMP-2223 Added __files to docker

build.gradle, config/checkstyle/checkstyle.xml, src/main/java/uk/gov/hmcts/darts/stub/services/controllers/WiremockRequestForwardingController.java, wiremock/mappings/arm/v3_UpdateMetadata.json, wiremock/mappings/arm/v3_UpdateMetadata_alt1.json, wiremock/mappings/dar/dar_mapping.json
The app gateway is trying to upgrade the http protocol to version 2.  
```
[ ] Yes
[x] No
```
=> DMP-1845: Forcing http 1.1

darts-stub-services.postman_collection.json, wiremock/mappings/arm/v3_UpdateMetadata.json, wiremock/mappings/arm/v3_UpdateMetadata_alt1.json
https://tools.hmcts.net/jira/browse/DMP-2388
Change the minimum year in Disposition Stub from 2024 to 1924
```
[ ] Yes
[X] No
```
=> DMP-2388 Changed validation year

charts/darts-stub-services/Chart.yaml, charts/darts-stub-services/values.yaml
https://tools.hmcts.net/jira/browse/DMP-2571
As title
```
[ ] Yes
[x] No
```
=> Fixing ingress host to match auto DNS entry

darts-stub-services.postman_collection.json, wiremock/mappings/arm/v1_availableEntitlementProfiles.json, wiremock/mappings/arm/v1_selectEntitlementProfile.json
DMP-3144
DMP-3145
Stub endpoints for ARM Authorisation service
```
[ ] Yes
[x] No
```
=> DMP-3144 : ARM Authorisation endpoints

wiremock/mappings/arm/v1_token.json
DMP-3359
ARM token endpoint protocol changes
```
[ ] Yes
[x] No
```
=> DMP-3359 : ARM Token endpoint protocol changes

build.gradle, config/pmd/main-ruleset.xml, config/pmd/test-ruleset.xml, docker-compose.yml, src/integrationTest/java/uk/gov/hmcts/darts/stub/services/IntegrationTestBase.java, src/integrationTest/java/uk/gov/hmcts/darts/stub/services/UpdatedProxyTest.java, src/integrationTest/java/uk/gov/hmcts/darts/stub/services/WiremockProxyTest.java, src/integrationTest/java/uk/gov/hmcts/darts/stub/services/controllers/GetWelcomeTest.java, src/integrationTest/java/uk/gov/hmcts/darts/stub/services/openapi/OpenAPIPublisherTest.java, src/main/java/uk/gov/hmcts/darts/stub/services/config/WireMockServerConfig.java, src/main/java/uk/gov/hmcts/darts/stub/services/controllers/WiremockRequestForwardingController.java, src/main/resources/application.yaml, wiremock/mappings/arm/v3_UpdateMetadata.json
https://tools.hmcts.net/jira/browse/DMP-3538
Add new dummy values when updating the arm endpoint.  Also tidied up the code to align with our PMD rules.
```
[ ] Yes
[ ] No
```
=> DMP-3538: Add new dummy arm update values and correct PMD issues

darts-stub-services.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/stub/services/UpdatedProxyTest.java, wiremock/mappings/arm/v3_UpdateMetadata.json
DMP-3976
Update ARM Updatemetadata attribute name
```
[ ] Yes
[x] No
```
=> DMP-3976 : change updatemetadata retention attributes

wiremock/mappings/arm/v1_getStorageAccounts.json
>[Jira](https://tools.hmcts.net/jira/browse/DMP-3796)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=183)
This diff introduces a new JSON mapping file for WireMock that defines a mock response for a POST request to the endpoint `/api/v1/getStorageAccounts`. The file includes detailed mock response data, simulating the structure and content expected from a real API call.
- **New File Created**: `v1_getStorageAccounts.json`.
- **Request Definition**:
- **Method**: POST
- **Headers**: Content-Type set to `application/json`
- **URL Path**: `/api/v1/getStorageAccounts`
- **Body Patterns**: Matches a JSON object with `onlyKeyAccessType` as `false` and `storageType` as `1`.
- **Response Definition**:
- **Status**: 200 OK
- **Headers**: Content-Type set …
=> DMP-3796: ARM RPO - Stub for new ARM endpoint - getStorageAccounts

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/publish-openapi.yaml, build.gradle
=> Upgrading to Java 21
